AutoBiographerEnum = {
  DamageOrHealingCategory = {
    DamageDealt = 0,
    DamageTaken = 1,
    HealingDealtToOthers = 2,
    HealingDealtToSelf = 3,
    HealingTaken = 4,
  },
  EventType = {
    Battleground = 0,
    Death = 1,
    Level = 2,
    Gathering = 3,
    Guild = 4,
    Instance = 5,
    Item = 6,
    Kill = 7,
    Map = 8,
    Miscellaneous = 9,
    Money = 10,
    Pvp = 11,
    Quest = 12,
    Skill = 13,
    Spell = 14,
    Talent = 15,
    Time = 16,
    Xp = 17
  },
  EventSubType = {
    BossKill = 0,
    FirstKill = 1,
    GuildJoined = 2,
    GuildLeft = 3,
    GuildRankChanged = 4,
    LevelUp = 5,
    PlayerDeath = 6,
    QuestTurnIn = 7,
    SkillMilestone = 8,
    SpellLearned = 9,
    SubZoneFirstVisit = 10,
    ZoneFirstVisit = 11,
  },
  LogLevel = {
    Verbose = 0,
    Debug = 1,
    Information = 2,
    Warning = 3,
    Error = 4,
    Fatal = 5
  },
  TimeTrackingType = {
    Afk = 0,
    Casting = 1,
    DeadOrGhost = 2,
    InCombat = 3,
    LoggedIn = 4,
    OnTaxi = 5,
  },
}